#Numpy 학습하기
1주차 (11월 23일)

**Numpy의 array는 python의 list보다 속도가 빠르다**


> **python은 겉보기엔 하나의 박스에 데이터가 정리되어 담긴것 같지만, 현실은 ADHD가 물건을 어질러 놓고 물건위치가 적인 메모만 같고있는것 같다.** 그래서 원소들은 서로다른 메모리에 저장되어있고, 리스트에는 주소만 담겨있다.


> **반면에 Numpy는 실제로 보이는것처럼 [1,2,3] 이렇게 메모리가 하나의 박스에 담겨 저장**되기때문에 바로 옆에 가면 다음데이터여서 처리가 빠르다.




In [2]:
import numpy as np
vec=np.array([1,2,3])
print(vec)
print(vec.shape)  #크기 (행x열)
print(vec.ndim) #차원

mat=np.array([1,2,3],[10,20,30])
print(mat)
print(mat.shape)
print(mat.ndim)

[1 2 3]
(3,)
1


**ndim=차원     shape=크기 (행,열)**


> 벡터는 (3,1)같이 나올거같지만 관례가 벡터는 생략하고 갯수만 표현한다 => **(3,)**

벡터 = 그냥 숫자 3개 담긴 리스트
화살표 방향? 그런 거 없음  
필요하면 reshape로 바꾸면 됨 초기는 (1x3) 가로.ver

=============================================================

##ndarray의 초기화
*반드시 괄호안에 또 (n,m) 괄호를 싸서 넣어야함*  

zeros((행,열))  - 행x열 크기의 0 행렬  
ones((행,열))   - 행x열 크기의 1만 들어있는 행렬   
full((행,열), k) - 행x열 크기의 k값만 들어있는 행렬  
eye(행) - 행x열의 크기에 주대각선만 1인 행렬 => **단위행렬**  
np.random.random((행,렬)) - 행x열 크기의 랜덤한 난수 행렬



In [6]:
np1=np.zeros((2,2))
np2=np.ones((1,3))
np3=np.ones((3,1))
np4=np.full((3,),3)
np6=np.eye(3)
np5=np.random.random((2,2))

print(np1,np2,np3,np4,np5,np6,sep="\n")
#np2,np3을 유의해서 볼것, 2차원 배열임!!

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]]
[[1.]
 [1.]
 [1.]]
[3 3 3]
[[0.54431057 0.4039307 ]
 [0.65197078 0.38225678]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##vec 나열하기 - arange(i,j,k)  
python의 range랑 완전히 똑같음, **특이한점은 소숫점도 가능하다!**




In [8]:
nlist=np.arange(1,11)
ilist=np.arange(0.1,1.1,0.2)
print(nlist,ilist,sep="\n")

[ 1  2  3  4  5  6  7  8  9 10]
[0.1 0.3 0.5 0.7 0.9]


##np.array(np.arange(30)).reshape((5,6))


>**✔  벡터, 행렬, 3D 텐서… 뭐든 다 reshape 가능해!**

In [11]:
ex=np.array(np.arange(30)).reshape((5,6))
print(ex)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

##넘파이 슬라이싱
기존 규칙은 python과 동일  


> **numpy는 이중리스트로 보지 않고, 하나의 연속된 데이터(큰 블록)를 좌표로 잘라내는 방식**


👉 행과 열을 동시에 슬라이싱하는 문법이 존재함 (, 사용)  
👉 파이썬 리스트에는 없음

In [12]:
print(ex[0,:]) #행만 추출
print(ex[:,-1]) #열만 추출

[0 1 2 3 4 5]
[ 5 11 17 23 29]


펜시 인덱싱 - 좌표값만 뽑아오기
ex[[1,2][3,4]]=[9,16]  

> **!=mat[9,16]==error??**  
이건 사람 입장에서 “결과 값”을 기준으로 생각한 사고방식인데
numpy는 절대 그렇게 하지 않아.


*그냥 외우자!!*

In [13]:
print(ex[[1,2],[3,4]])

[ 9 16]
